### ISSUE TITLE
Some functions in utils/misc.py are not implemented

### ISSUE THREAD

**Issue by fengyuentau** [nashory/DeLF-pytorch#10]
Functions declared in var `__all__` in `utils/misc.py`, which are `get_mean_and_std` and `init_param`, are not implemented. To start training, those two need to be removed from `__all__`.

**Comment by anmol4210** [comment]
Please find below attached the code for above mentioned two functions

```
def get_mean_and_std(dataset):
    '''Compute the mean and std value of dataset.'''
    dataloader = torch.utils.data.DataLoader(
        dataset, batch_size=1, shuffle=True, num_workers=2)

    mean = torch.zeros(3)
    std = torch.zeros(3)
    print('==> Computing mean and std..')
    for inputs, targets in dataloader:
        for i in range(3):
            mean[i] += inputs[:, i, :, :].mean()
            std[i] += inputs[:, i, :, :].std()
    mean.div_(len(dataset))
    std.div_(len(dataset))
    return mean, std


def init_params(net):
    '''Init layer parameters.'''
    for m in net.modules():
        if isinstance(m, nn.Conv2d):
            init.kaiming_normal(m.weight, mode='fan_out')
            if m.bias:
                init.constant(m.bias, 0)
        elif isinstance(m, nn.BatchNorm2d):
            init.constant(m.weight, 1)
            init.constant(m.bias, 0)
        elif isinstance(m, nn.Linear):
            init.normal(m.weight, std=1e-3)
            if m.bias:
                init.constant(m.bias, 0)

```

**Comment by yunlongGao23** [comment]
> 请在下面找到上述两个功能的代码
> 
> ```
> def get_mean_and_std(dataset):
>     '''Compute the mean and std value of dataset.'''
>     dataloader = torch.utils.data.DataLoader(
>         dataset, batch_size=1, shuffle=True, num_workers=2)
> 
>     mean = torch.zeros(3)
>     std = torch.zeros(3)
>     print('==> Computing mean and std..')
>     for inputs, targets in dataloader:
>         for i in range(3):
>             mean[i] += inputs[:, i, :, :].mean()
>             std[i] += inputs[:, i, :, :].std()
>     mean.div_(len(dataset))
>     std.div_(len(dataset))
>     return mean, std
> 
> 
> def init_params(net):
>     '''Init layer parameters.'''
>     for m in net.modules():
>         if isinstance(m, nn.Conv2d):
>             init.kaiming_normal(m.weight, mode='fan_out')
>             if m.bias:
>                 init.constant(m.bias, 0)
>         elif isinstance(m, nn.BatchNorm2d):
>             init.constant(m.weight, 1)
>             init.constant(m.bias, 0)
>         elif isinstance(m, nn.Linear):
>             init.normal(m.weight, std=1e-3)
>             if m.bias:
>                 init.constant(m.bias, 0)
> ```



> Please find below attached the code for above mentioned two functions
> 
> ```
> def get_mean_and_std(dataset):
>     '''Compute the mean and std value of dataset.'''
>     dataloader = torch.utils.data.DataLoader(
>         dataset, batch_size=1, shuffle=True, num_workers=2)
> 
>     mean = torch.zeros(3)
>     std = torch.zeros(3)
>     print('==> Computing mean and std..')
>     for inputs, targets in dataloader:
>         for i in range(3):
>             mean[i] += inputs[:, i, :, :].mean()
>             std[i] += inputs[:, i, :, :].std()
>     mean.div_(len(dataset))
>     std.div_(len(dataset))
>     return mean, std
> 
> 
> def init_params(net):
>     '''Init layer parameters.'''
>     for m in net.modules():
>         if isinstance(m, nn.Conv2d):
>             init.kaiming_normal(m.weight, mode='fan_out')
>             if m.bias:
>                 init.constant(m.bias, 0)
>         elif isinstance(m, nn.BatchNorm2d):
>             init.constant(m.weight, 1)
>             init.constant(m.bias, 0)
>         elif isinstance(m, nn.Linear):
>             init.normal(m.weight, std=1e-3)
>             if m.bias:
>                 init.constant(m.bias, 0)
> ```

hi,bro. i think that "misc.py" lacks of function"bar".i will be appreciated if you can tell me the code. Have a nice day bro!
