### ISSUE TITLE
train PCA

### ISSUE THREAD

**Issue by zzzz3800** [nashory/DeLF-pytorch#17]
error

**Comment by fatemeakbari** [comment]
Hello, I have the same problem, do you find a solution?

**Comment by zzzz3800** [comment]
> Hello, I have the same problem, do you find a solution?
Hello, I haven't found a solution yet.I haven't been debugging this program in the last few months. But recently I maybe debug it again. I'll reply you if I find a solution.

**Comment by fatemeakbari** [comment]
Thanks a lot

**Comment by zzzz3800** [comment]
> Thanks a lot

Hello, I recently debugged the program and still get the original error. Have you debugged?

**Comment by fatemeakbari** [comment]
Hello, I didn't continue, but one idea that may help you, use of "iter" over your dataloader instead loop over dataloader in extractor.py file.

**Comment by zzzz3800** [comment]
> Hello, I didn't continue, but one idea that may help you, use of "iter" over your dataloader instead loop over dataloader in extractor.py file.

Thanks a lot

**Comment by zzzz3800** [comment]
> Hello, I didn't continue, but one idea that may help you, use of "iter" over your dataloader instead loop over dataloader in extractor.py file.

Hello. Many download links of LF and LC datasets  are invalid. Have you successfully downloaded the dataset? Could you share it?

**Comment by fatemeakbari** [comment]
Hello, I train on a custom dataset

**Comment by zzzz3800** [comment]
> Hello, I train on a custom dataset

Thanks a lot
