### ISSUE TITLE
error:floor_vml_cpu not implemented for 'Long' 

### ISSUE THREAD

**Issue by CTianyou** [nashory/DeLF-pytorch#18]
In train PCA, the error "floor_vml_cpu not implemented for 'Long'"  ocur.

**Comment by yanbai1993** [comment]
In delf_helper.py line 26-27, change 
    x = torch.floor(torch.arange(0., w*h) / w)
    y = torch.arange(0., w).repeat(h)

to

**Comment by yanbai1993** [comment]
In delf_helper.py line 26-27, change
x = torch.floor(torch.arange(0, w*h) / w)
y = torch.arange(0, w).repeat(h)
to
 x = torch.floor(torch.arange(0., w*h) / w)
y = torch.arange(0., w).repeat(h)
