### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by ducha-aiki** [nashory/DeLF-pytorch#35]
Hi,

Thank you for the cool re-implementation! May I ask you about the license on your code? 
I would like to port to to the kornia local features https://kornia.readthedocs.io/en/latest/feature.html

--
Best, Dmytro

**Comment by nashory** [comment]
Hi, 

My code has no licence and you are free to go ;)

**Comment by ducha-aiki** [comment]
Hi,

Unfortunately, no licence in some countries means "no use is allowed" :(

See here https://www.gnu.org/licenses/license-list.html#NoLicense

> No license (#NoLicense)
If source code does not carry a license to give users the four essential freedoms, then unless it has been explicitly and validly placed in the public domain, it is not free software.
>Some developers think that code with no license is automatically in the public domain. That is not true under today's copyright law; rather, all copyrightable works are copyrighted by default. This includes programs. Absent a license to grant users freedom, they don't have any. In some countries, users that download code with no license may infringe copyright merely by compiling it or running it.
>In order for a program to be free, its copyright holders must explicitly grant users the four essential freedoms. The document with which they do so is called a free software license. This is what free software licenses are for.

So if you is OK with anyone using your code, could you please put the MIT or Apache license? Thank you a lot :)

**Comment by nashory** [comment]
I added LICENSE :)

**Comment by ducha-aiki** [comment]
Thank you a lot!
