### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by caffeinism** [nashory/DeLF-pytorch#9]
Hello! I am always looking at your beneficial repository.

I'm wondering what difference between the dataset used in the pretrain process and finetuning process.

One uses full and one uses clean, what is the difference between this two datasets?

**Comment by daijing5763** [comment]
how can i prepare the dataset?

**Comment by QinZiwen** [comment]
I have same problem

**Comment by QinZiwen** [comment]
Figure 4 in parer, reference: https://arxiv.org/pdf/1612.06321.pdf
